/* Generated by the Nim Compiler v2.0.4 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI536871089 = {size: 0, kind: 24, base: null, node: null, finalizer: null};
var NTI671088644 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI671088643 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI536871088 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI536871159 = {size: 0, kind: 24, base: null, node: null, finalizer: null};
var NTI33554466 = {size: 0,kind: 1,base: null,node: null,finalizer: null};
var NTI536871134 = {size: 0, kind: 24, base: null, node: null, finalizer: null};
var NTI872415275 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI536871094 = {size: 0, kind: 24, base: null, node: null, finalizer: null};
var NTI33554449 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NTI536871031 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI536871032 = {size: 0, kind: 24, base: null, node: null, finalizer: null};
var NTI536871027 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33554445 = {size: 0,kind: 36,base: null,node: null,finalizer: null};
var NTI536870926 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI687866335 = {size: 0, kind: 24, base: null, node: null, finalizer: null};
var NTI33554435 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI687866266 = {size: 0, kind: 24, base: null, node: null, finalizer: null};
NTI687866266.base = NTI33554435;
NTI687866335.base = NTI33554435;
var NNI536870926 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554445, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554435, name: "Field1", sons: null}]};
NTI536870926.node = NNI536870926;
var NNI536871031 = {kind: 2, len: 3, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "start", len: 0, typ: NTI33554445, name: "start", sons: null}, 
{kind: 1, offset: "duration", len: 0, typ: NTI33554445, name: "duration", sons: null}, 
{kind: 1, offset: "data", len: 0, typ: NTI33554435, name: "data", sons: null}]};
NTI536871031.node = NNI536871031;
NTI536871032.base = NTI536871031;
var NNI536871027 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "notes", len: 0, typ: NTI536871032, name: "notes", sons: null}, 
{kind: 1, offset: "duration", len: 0, typ: NTI33554445, name: "duration", sons: null}]};
NTI536871027.node = NNI536871027;
var NNI872415275 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554445, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554445, name: "Field1", sons: null}]};
NTI872415275.node = NNI872415275;
NTI536871094.base = NTI872415275;
NTI536871134.base = NTI33554466;
var NNI671088644 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI671088644.node = NNI671088644;
NTI671088643.base = NTI671088644;
var NNI536871088 = {kind: 2, len: 3, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "data", len: 0, typ: NTI33554435, name: "data", sons: null}, 
{kind: 1, offset: "idx", len: 0, typ: NTI33554435, name: "idx", sons: null}, 
{kind: 1, offset: "gate", len: 0, typ: NTI671088643, name: "gate", sons: null}]};
NTI536871088.node = NNI536871088;
NTI536871159.base = NTI536871088;
NTI536871089.base = NTI536871088;

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_33557268, src_33557269, ti_33557270) {
  var result_33557279 = null;

    switch (ti_33557270.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer_33557259(ti_33557270))) {
      result_33557279 = src_33557269;
      }
      else {
        result_33557279 = [src_33557269[0], src_33557269[1]];
      }
      
      break;
    case 19:
            if (dest_33557268 === null || dest_33557268 === undefined) {
        dest_33557268 = {};
      }
      else {
        for (var key in dest_33557268) { delete dest_33557268[key]; }
      }
      for (var key in src_33557269) { dest_33557268[key] = src_33557269[key]; }
      result_33557279 = dest_33557268;
    
      break;
    case 18:
    case 17:
      if (!((ti_33557270.base == null))) {
      result_33557279 = nimCopy(dest_33557268, src_33557269, ti_33557270.base);
      }
      else {
      if ((ti_33557270.kind == 17)) {
      result_33557279 = (dest_33557268 === null || dest_33557268 === undefined) ? {m_type: ti_33557270} : dest_33557268;
      }
      else {
        result_33557279 = (dest_33557268 === null || dest_33557268 === undefined) ? {} : dest_33557268;
      }
      }
      nimCopyAux(result_33557279, src_33557269, ti_33557270.node);
      break;
    case 4:
    case 16:
            if(ArrayBuffer.isView(src_33557269)) { 
        if(dest_33557268 === null || dest_33557268 === undefined || dest_33557268.length != src_33557269.length) {
          dest_33557268 = new src_33557269.constructor(src_33557269);
        } else {
          dest_33557268.set(src_33557269, 0);
        }
        result_33557279 = dest_33557268;
      } else {
        if (src_33557269 === null) {
          result_33557279 = null;
        }
        else {
          if (dest_33557268 === null || dest_33557268 === undefined || dest_33557268.length != src_33557269.length) {
            dest_33557268 = new Array(src_33557269.length);
          }
          result_33557279 = dest_33557268;
          for (var i = 0; i < src_33557269.length; ++i) {
            result_33557279[i] = nimCopy(result_33557279[i], src_33557269[i], ti_33557270.base);
          }
        }
      }
    
      break;
    case 24:
    case 27:
            if (src_33557269 === null) {
        result_33557279 = null;
      }
      else {
        if (dest_33557268 === null || dest_33557268 === undefined || dest_33557268.length != src_33557269.length) {
          dest_33557268 = new Array(src_33557269.length);
        }
        result_33557279 = dest_33557268;
        for (var i = 0; i < src_33557269.length; ++i) {
          result_33557279[i] = nimCopy(result_33557279[i], src_33557269[i], ti_33557270.base);
        }
      }
    
      break;
    case 28:
            if (src_33557269 !== null) {
        result_33557279 = src_33557269.slice(0);
      }
    
      break;
    default: 
      result_33557279 = src_33557269;
      break;
    }

  return result_33557279;

}
    var sharps_687865887 = new Uint8Array([0, 1, 3, 4, 6, 7, 8, 10, 11, 13, 14, 16]);
    var flats_687865888 = new Uint8Array([0, 2, 3, 5, 6, 7, 9, 10, 12, 13, 15, 16]);

function toJSStr(s_33556901) {
  var result_33556902 = null;

    var res_33556943 = newSeq_33556919((s_33556901).length);
    var i_33556944 = 0;
    var j_33556945 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33556944 < (s_33556901).length)) break Label2;
          var c_33556946 = s_33556901[i_33556944];
          if ((c_33556946 < 128)) {
          res_33556943[j_33556945] = String.fromCharCode(c_33556946);
          i_33556944 += 1;
          }
          else {
            var helper_33556959 = newSeq_33556919(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33556960 = c_33556946.toString(16);
                  if ((((code_33556960) == null ? 0 : (code_33556960).length) == 1)) {
                  helper_33556959.push("%0");;
                  }
                  else {
                  helper_33556959.push("%");;
                  }
                  
                  helper_33556959.push(code_33556960);;
                  i_33556944 += 1;
                  if ((((s_33556901).length <= i_33556944) || (s_33556901[i_33556944] < 128))) {
                  break Label3;
                  }
                  
                  c_33556946 = s_33556901[i_33556944];
                }
            };
++excHandler;
            try {
            res_33556943[j_33556945] = decodeURIComponent(helper_33556959.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            res_33556943[j_33556945] = helper_33556959.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33556945 += 1;
        }
    };
    if (res_33556943.length < j_33556945) { for (var i = res_33556943.length ; i < j_33556945 ; ++i) res_33556943.push(null); }
               else { res_33556943.length = j_33556945; };
    result_33556902 = res_33556943.join("");

  return result_33556902;

}

function mnewString(len_33557003) {
        var result = new Array(len_33557003);
    for (var i = 0; i < len_33557003; i++) {result[i] = 0;}
    return result;
  

  
}

function rawEcho() {
          var buf = "";
      for (var i = 0; i < arguments.length; ++i) {
        buf += toJSStr(arguments[i]);
      }
      console.log(buf);
    

  
}
import { el } from "@elemaudio/core" 

function isFatPointer_33557259(ti_33557260) {
  var result_33557261 = false;

  BeforeRet: {
    result_33557261 = !((ConstSet1[ti_33557260.base.kind] != undefined));
    break BeforeRet;
  };

  return result_33557261;

}

function nimCopyAux(dest_33557272, src_33557273, n_33557274) {
    switch (n_33557274.kind) {
    case 0:
      break;
    case 1:
            dest_33557272[n_33557274.offset] = nimCopy(dest_33557272[n_33557274.offset], src_33557273[n_33557274.offset], n_33557274.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_33557274.sons.length; i++) {
      nimCopyAux(dest_33557272, src_33557273, n_33557274.sons[i]);
    }
    
      break;
    case 3:
            dest_33557272[n_33557274.offset] = nimCopy(dest_33557272[n_33557274.offset], src_33557273[n_33557274.offset], n_33557274.typ);
      for (var i = 0; i < n_33557274.sons.length; ++i) {
        nimCopyAux(dest_33557272, src_33557273, n_33557274.sons[i][1]);
      }
    
      break;
    }

  
}

function midiOffsets_687866392(scale_687866393) {
    var Temporary1;

  var result_687866394 = [];

    switch (scale_687866393) {
    case 0:
      Temporary1 = [0, 2, 4, 5, 7, 9, 11];
      break;
    case 1:
      Temporary1 = [0, 2, 3, 5, 7, 8, 10];
      break;
    case 2:
      Temporary1 = [0, 2, 3, 5, 7, 8, 11];
      break;
    case 3:
      Temporary1 = [0, 2, 4, 7, 9];
      break;
    case 4:
      Temporary1 = [0, 3, 5, 7, 10];
      break;
    case 5:
      Temporary1 = [0, 3, 5, 6, 7, 10];
      break;
    }
    result_687866394 = nimCopy(null, Temporary1, NTI687866266);

  return result_687866394;

}

function scale_687866467(baseNoteMidi_687866468, scale_687866469) {
  var result_687866470 = [];

    var offsets_687866471 = midiOffsets_687866392(scale_687866469);
    Label1: {
      var j_687866476 = 0;
      var i_536871683 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_536871683 < 3)) break Label3;
            j_687866476 = i_536871683;
            Label4: {
              var i_687866480 = 0;
              var i_536871680 = 0;
              var L_536871681 = (offsets_687866471).length;
              Label5: {
                  Label6: while (true) {
                  if (!(i_536871680 < L_536871681)) break Label6;
                    i_687866480 = offsets_687866471[i_536871680];
                    result_687866470.push(((i_687866480 + baseNoteMidi_687866468) + (j_687866476 * 12)));;
                    i_536871680 += 1;
                  }
              };
            };
            i_536871683 += 1;
          }
      };
    };

  return result_687866470;

}

function find_687865889(a_687865892, item_687865893) {
  var result_687865894 = 0;

  BeforeRet: {
    result_687865894 = 0;
    Label1: {
      var i_687865937 = 0;
      var i_536871687 = 0;
      Label2: {
          Label3: while (true) {
          if (!true) break Label3;
            i_687865937 = a_687865892[i_536871687];
            if ((i_687865937 == item_687865893)) {
            break BeforeRet;
            }
            
            result_687865894 += 1;
            if ((11 <= i_536871687)) {
            break Label2;
            }
            
            i_536871687 += 1;
          }
      };
    };
    result_687865894 = (-1);
  };

  return result_687865894;

}

function toMidi_687865884(note_687865885) {
  var result_687865886 = 0;

    var toneIndex_687865980 = find_687865889(sharps_687865887, note_687865885.Field0);
    if ((toneIndex_687865980 == (-1))) {
    toneIndex_687865980 = find_687865889(flats_687865888, note_687865885.Field0);
    }
    
    result_687865886 = (((note_687865885.Field1 + 1) * 12) + toneIndex_687865980);

  return result_687865886;

}

function scale_687866485(baseNote_687866486, scaleType_687866487) {
  var result_687866488 = [];

    result_687866488 = nimCopy(null, scale_687866467(toMidi_687865884(baseNote_687866486), scaleType_687866487), NTI687866335);

  return result_687866488;

}

function note_536870918(duration_536870919, scaleIndex_536870920) {
  var result_536870924 = {Field0: 0.0, Field1: 0};

    var colontmp__536871689 = duration_536870919;
    var colontmp__536871690 = s_536870916[(scaleIndex_536870920 - 1)];
    result_536870924 = nimCopy(result_536870924, {Field0: colontmp__536871689, Field1: colontmp__536871690}, NTI536870926);

  return result_536870924;

}

function brk_536870947(duration_536870948) {
  var result_536870950 = {Field0: 0.0, Field1: 0};

    var colontmp__536871691 = duration_536870948;
    var colontmp__536871692 = bassNull_536870917;
    result_536870950 = nimCopy(result_536870950, {Field0: colontmp__536871691, Field1: colontmp__536871692}, NTI536870926);

  return result_536870950;

}

function sharp_536870942(n_536870944) {
  var result_536870946 = {Field0: 0.0, Field1: 0};

    var colontmp__536871693 = n_536870944["Field0"];
    var colontmp__536871694 = (n_536870944["Field1"] + 1);
    result_536870946 = nimCopy(result_536870946, {Field0: colontmp__536871693, Field1: colontmp__536871694}, NTI536870926);

  return result_536870946;

}

function HEX26_536870966(x_536870968, y_536870969) {
  var result_536870970 = [];

    result_536870970 = new Array(((x_536870968).length + (y_536870969).length)); for (var i = 0 ; i < ((x_536870968).length + (y_536870969).length) ; ++i) { result_536870970[i] = {Field0: 0.0, Field1: 0}; }    Label1: {
      var i_536870989 = 0;
      var colontmp__536871696 = 0;
      colontmp__536871696 = ((x_536870968).length - 1);
      var res_536871698 = 0;
      Label2: {
          Label3: while (true) {
          if (!(res_536871698 <= colontmp__536871696)) break Label3;
            i_536870989 = res_536871698;
            result_536870970[i_536870989] = nimCopy(result_536870970[i_536870989], x_536870968[i_536870989], NTI536870926);
            res_536871698 += 1;
          }
      };
    };
    Label4: {
      var i_536870997 = 0;
      var colontmp__536871701 = 0;
      colontmp__536871701 = ((y_536870969).length - 1);
      var res_536871702 = 0;
      Label5: {
          Label6: while (true) {
          if (!(res_536871702 <= colontmp__536871701)) break Label6;
            i_536870997 = res_536871702;
            result_536870970[(i_536870997 + (x_536870968).length)] = nimCopy(result_536870970[(i_536870997 + (x_536870968).length)], y_536870969[i_536870997], NTI536870926);
            res_536871702 += 1;
          }
      };
    };

  return result_536870970;

}

function newSeq_33556919(len_33556921) {
  var result_33556922 = [];

    result_33556922 = new Array(len_33556921); for (var i = 0 ; i < len_33556921 ; ++i) { result_33556922[i] = null; }
  return result_33556922;

}

function timedTrigger_671088802(start_671088803, dur_671088804, key_671088805) {
  var result_671088806 = null;

    var t_671088807 = el.div(el.time(), el.sr());
    var startNode_671088808 = el.const({value: start_671088803, key: toJSStr((key_671088805 || []).concat([95,115,116,97,114,116] || []))});
    var endNode_671088809 = el.const({value: (start_671088803 + dur_671088804), key: toJSStr((key_671088805 || []).concat([95,101,110,100] || []))});
    result_671088806 = el.mul(el.ge(t_671088807, startNode_671088808), el.le(t_671088807, endNode_671088809));

  return result_671088806;

}

function addChars_301990090(result_301990092, result_301990092_Idx, x_301990093, start_301990094, n_301990095) {
    var Temporary1;

    var old_301990096 = (result_301990092[result_301990092_Idx]).length;
    if (result_301990092[result_301990092_Idx].length < (Temporary1 = (old_301990096 + n_301990095), Temporary1)) { for (var i = result_301990092[result_301990092_Idx].length; i < Temporary1; ++i) result_301990092[result_301990092_Idx].push(0); }
         else {result_301990092[result_301990092_Idx].length = Temporary1; };
    Label2: {
      var iHEX60gensym4_301990110 = 0;
      var i_536871722 = 0;
      Label3: {
          Label4: while (true) {
          if (!(i_536871722 < n_301990095)) break Label4;
            iHEX60gensym4_301990110 = i_536871722;
            result_301990092[result_301990092_Idx][(old_301990096 + iHEX60gensym4_301990110)] = x_301990093.charCodeAt((start_301990094 + iHEX60gensym4_301990110));
            i_536871722 += 1;
          }
      };
    };

  
}

function addChars_301990086(result_301990088, result_301990088_Idx, x_301990089) {
    addChars_301990090(result_301990088, result_301990088_Idx, x_301990089, 0, ((x_301990089) == null ? 0 : (x_301990089).length));

  
}

function addInt_301990111(result_301990112, result_301990112_Idx, x_301990113) {
    addChars_301990086(result_301990112, result_301990112_Idx, ((x_301990113) + ""));

  
}

function addInt_301990129(result_301990130, result_301990130_Idx, x_301990131) {
    addInt_301990111(result_301990130, result_301990130_Idx, BigInt(x_301990131));

  
}

function HEX24_369098760(x_369098761) {
  var result_369098762 = [[]];

    addInt_301990129(result_369098762, 0, x_369098761);

  return result_369098762[0];

}

function createSequencer_536871109(s_536871111, initData_536871112, trackCount_536871113, bpm_536871114, repetitions_536871115, startTime_536871116, seqKey_536871117, debug_536871118) {
  var result_536871136 = ({sequence: ({notes: [], duration: 0.0}), initData: 0, trackCount: 0, bpm: 0.0, repetitions: 0, startTime: 0.0, seqKey: [], debug: false, secPerBeat: 0.0, seqDuration: 0.0, noteIntervals: [], tracks: [], playingNotes: [], currentTrackIdx: 0});

    result_536871136.sequence = nimCopy(result_536871136.sequence, s_536871111, NTI536871027);
    result_536871136.initData = initData_536871112;
    result_536871136.trackCount = trackCount_536871113;
    result_536871136.bpm = bpm_536871114;
    result_536871136.repetitions = repetitions_536871115;
    result_536871136.startTime = startTime_536871116;
    result_536871136.seqKey = nimCopy(null, seqKey_536871117, NTI33554449);
    result_536871136.debug = debug_536871118;
    var secPerBeat_536871137 = (60.0 / bpm_536871114);
    result_536871136.secPerBeat = secPerBeat_536871137;
    var seqDuration_536871138 = (s_536871111.duration * secPerBeat_536871137);
    result_536871136.seqDuration = seqDuration_536871138;
    var noteIntervals_536871143 = [];
    Label1: {
      var i_536871185 = 0;
      var note_536871186 = ({start: 0.0, duration: 0.0, data: 0});
      var i_536871706 = 0;
      var L_536871707 = (s_536871111.notes).length;
      Label2: {
          Label3: while (true) {
          if (!(i_536871706 < L_536871707)) break Label3;
            i_536871185 = i_536871706;
            note_536871186 = nimCopy(note_536871186, s_536871111.notes[i_536871706], NTI536871031);
            var start_536871187 = ((note_536871186.start * secPerBeat_536871137) - seqDuration_536871138);
            var finish_536871188 = (start_536871187 + (note_536871186.duration * secPerBeat_536871137));
            if ((0.0 < finish_536871188)) {
            noteIntervals_536871143.push({Field0: start_536871187, Field1: finish_536871188});;
            }
            
            i_536871706 += 1;
          }
      };
    };
    var playingNotes_536871197 = [];
    Label4: {
      var i_536871203 = 0;
      var note_536871204 = ({start: 0.0, duration: 0.0, data: 0});
      var i_536871710 = 0;
      var L_536871711 = (s_536871111.notes).length;
      Label5: {
          Label6: while (true) {
          if (!(i_536871710 < L_536871711)) break Label6;
            i_536871203 = i_536871710;
            note_536871204 = nimCopy(note_536871204, s_536871111.notes[i_536871710], NTI536871031);
            var start_536871205 = (note_536871204.start * secPerBeat_536871137);
            var finish_536871206 = (start_536871205 + (note_536871204.duration * secPerBeat_536871137));
            noteIntervals_536871143.push({Field0: start_536871205, Field1: finish_536871206});;
            playingNotes_536871197.push(false);;
            i_536871710 += 1;
          }
      };
    };
    result_536871136.noteIntervals = nimCopy(null, noteIntervals_536871143, NTI536871094);
    result_536871136.playingNotes = nimCopy(null, playingNotes_536871197, NTI536871134);
    var tracks_536871220 = [];
    Label7: {
      var i_536871225 = 0;
      var i_536871714 = 0;
      Label8: {
          Label9: while (true) {
          if (!(i_536871714 < trackCount_536871113)) break Label9;
            i_536871225 = i_536871714;
            tracks_536871220.push({data: initData_536871112, idx: i_536871225, gate: timedTrigger_671088802(0.0, 0.0, (seqKey_536871117 || []).concat(HEX24_369098760(i_536871225) || []))});;
            i_536871714 += 1;
          }
      };
    };
    result_536871136.tracks = nimCopy(null, tracks_536871220, NTI536871159);

  return result_536871136;

}

function HEX2BHEX3D_536871066(x_536871068, x_536871068_Idx, y_536871069) {
    x_536871068[x_536871068_Idx] = (x_536871068[x_536871068_Idx] + y_536871069);

  
}

function toSequence_536871030(melody_536871032, null_536871033) {
  var result_536871039 = ({notes: [], duration: 0.0});

    Label1: {
      var note_536871059 = {Field0: 0.0, Field1: 0};
      var i_536871726 = 0;
      var L_536871727 = (melody_536871032).length;
      Label2: {
          Label3: while (true) {
          if (!(i_536871726 < L_536871727)) break Label3;
            note_536871059 = melody_536871032[i_536871726];
            if (!((note_536871059.Field1 == null_536871033))) {
            var n_536871061 = {start: result_536871039.duration, duration: note_536871059.Field0, data: note_536871059.Field1};
            var Temporary4 = nimCopy(null, n_536871061, NTI536871031);
            result_536871039.notes.push(Temporary4);;
            }
            
            HEX2BHEX3D_536871066(result_536871039, "duration", note_536871059.Field0);
            i_536871726 += 1;
          }
      };
    };

  return result_536871039;

}

function toInt_33556014(f_33556015) {
    var Temporary1;

  var result_33556016 = 0;

    if ((0.0 <= f_33556015)) {
    Temporary1 = (((f_33556015 + 0.5)) | 0);
    }
    else {
    Temporary1 = (((f_33556015 - 0.5)) | 0);
    }
    
    result_33556016 = Temporary1;

  return result_33556016;

}

function getNextTrackIdx_536871446(s_536871448) {
  var result_536871449 = 0;

    result_536871449 = s_536871448.currentTrackIdx;
    s_536871448.currentTrackIdx = Math.trunc((s_536871448.currentTrackIdx + 1) % s_536871448.trackCount);

  return result_536871449;

}

function addQuoted_536871544(s_536871546, s_536871546_Idx, x_536871547) {
    addInt_301990129(s_536871546, s_536871546_Idx, x_536871547);

  
}

function collectionToString_536871529(x_536871531, prefix_536871532, separator_536871533, suffix_536871534) {
  var result_536871535 = [[]];

    result_536871535[0] = nimCopy(null, prefix_536871532, NTI33554449);
    var firstElement_536871536 = true;
    Label1: {
      var value_536871540 = 0;
      var i_536871745 = 0;
      var L_536871746 = (x_536871531).length;
      Label2: {
          Label3: while (true) {
          if (!(i_536871745 < L_536871746)) break Label3;
            value_536871540 = x_536871531[i_536871745];
            if (firstElement_536871536) {
            firstElement_536871536 = false;
            }
            else {
            result_536871535[0].push.apply(result_536871535[0], separator_536871533);;
            }
            
            addQuoted_536871544(result_536871535, 0, value_536871540);
            i_536871745 += 1;
          }
      };
    };
    result_536871535[0].push.apply(result_536871535[0], suffix_536871534);;

  return result_536871535[0];

}

function HEX24_536871525(x_536871527) {
  var result_536871528 = [];

    result_536871528 = nimCopy(null, collectionToString_536871529(x_536871527, [64,91], [44,32], [93]), NTI33554449);

  return result_536871528;

}

function currentNotes_536871373(s_536871375, currentTime_536871376) {
  var result_536871377 = [];

    var currentLoop_536871378 = Math.floor(((currentTime_536871376 - s_536871375.startTime) / s_536871375.seqDuration));
    if (((s_536871375.repetitions == 0) || (toInt_33556014(currentLoop_536871378) < s_536871375.repetitions))) {
    var seqTime_536871379 = (currentTime_536871376 - (currentLoop_536871378 * s_536871375.seqDuration));
    Label1: {
      var i_536871420 = 0;
      var n_536871421 = {Field0: 0.0, Field1: 0.0};
      var i_536871736 = 0;
      var L_536871737 = (s_536871375.noteIntervals).length;
      Label2: {
          Label3: while (true) {
          if (!(i_536871736 < L_536871737)) break Label3;
            i_536871420 = i_536871736;
            n_536871421 = nimCopy(n_536871421, s_536871375.noteIntervals[i_536871736], NTI872415275);
            if ((((n_536871421.Field0 - 0.1) <= seqTime_536871379) && (seqTime_536871379 < n_536871421.Field1))) {
            if (!(s_536871375.playingNotes[i_536871420])) {
            var note_536871422 = nimCopy(null, s_536871375.sequence.notes[i_536871420], NTI536871031);
            var start_536871423 = (n_536871421.Field0 + (currentLoop_536871378 * s_536871375.seqDuration));
            var nextTrackIdx_536871450 = getNextTrackIdx_536871446(s_536871375);
            s_536871375.tracks[nextTrackIdx_536871450].data = note_536871422.data;
            s_536871375.tracks[nextTrackIdx_536871450].gate = timedTrigger_671088802(start_536871423, (note_536871422.duration * s_536871375.secPerBeat), (s_536871375.seqKey || []).concat(HEX24_369098760(nextTrackIdx_536871450) || []));
            s_536871375.playingNotes[i_536871420] = true;
            }
            
            }
            else {
              if (s_536871375.playingNotes[i_536871420]) {
              s_536871375.playingNotes[i_536871420] = false;
              }
              
            }
            
            i_536871736 += 1;
          }
      };
    };
    if (s_536871375.debug) {
    var playing_536871455 = [];
    Label4: {
      var i_536871495 = 0;
      var v_536871496 = false;
      var i_536871741 = 0;
      var L_536871742 = (s_536871375.playingNotes).length;
      Label5: {
          Label6: while (true) {
          if (!(i_536871741 < L_536871742)) break Label6;
            i_536871495 = i_536871741;
            v_536871496 = s_536871375.playingNotes[i_536871741];
            if (v_536871496) {
            playing_536871455.push(i_536871495);;
            }
            
            i_536871741 += 1;
          }
      };
    };
    rawEcho(s_536871375.seqKey, [32], HEX24_369098760(s_536871375.currentTrackIdx), [32], HEX24_536871525(playing_536871455));
    }
    
    }
    
    result_536871377 = nimCopy(null, s_536871375.tracks, NTI536871089);

  return result_536871377;

}

function HEX40_671088648(val_671088649, key_671088650) {
  var result_671088651 = null;

    result_671088651 = el.const({value: val_671088649, key: toJSStr(key_671088650)});

  return result_671088651;

}

function toFrequency_687865986(midi_687865987) {
  var result_687865988 = 0.0;

    result_687865988 = (Math.pow(2.0, ((midi_687865987 - 69) / 12.0)) * 440.0);

  return result_687865988;

}

function HEX2BHEX3D_671088705(a_671088706, a_671088706_Idx, b_671088707) {
    a_671088706[a_671088706_Idx] = el.add(a_671088706[a_671088706_Idx], b_671088707);

  
}

function play_536871348(time_536871349) {
  var result_536871350 = null;

    var bassNotes_536871565 = currentNotes_536871373(bassSeq_536871347[0], time_536871349);
    var bassSound_536871566 = [HEX40_671088648(0.0, [98,97,115,115])];
    var bassGain_536871567 = [HEX40_671088648(0.0, [98,97,115,115,95,103,97,105,110])];
    Label1: {
      var n_536871588 = ({data: 0, idx: 0, gate: null});
      var i_536871731 = 0;
      var L_536871732 = (bassNotes_536871565).length;
      Label2: {
          Label3: while (true) {
          if (!(i_536871731 < L_536871732)) break Label3;
            n_536871588 = bassNotes_536871565[i_536871731];
            var fq_536871589 = HEX40_671088648(toFrequency_687865986(n_536871588.data), ([98] || []).concat(HEX24_369098760(n_536871588.idx) || []));
            var amount_536871590 = el.mul(fq_536871589, 2.41);
            var fq2_536871591 = el.add(fq_536871589, el.mul(el.saw(el.add(fq_536871589, el.mul(el.mul(el.cycle(0.3), fq_536871589), 0.01))), amount_536871590));
            var sound_536871592 = el.lowpass(el.mul(fq_536871589, 2.5), el.const({value: 2.0}), el.mul(el.triangle(fq2_536871591), 0.5));
            var env_536871593 = el.adsr(el.const({value: 0.3}), el.const({value: 0.3}), el.const({value: 0.6}), el.const({value: release_536871027}), n_536871588.gate);
            HEX2BHEX3D_671088705(bassSound_536871566, 0, el.mul(sound_536871592, env_536871593));
            HEX2BHEX3D_671088705(bassGain_536871567, 0, env_536871593);
            i_536871731 += 1;
          }
      };
    };
    var bass_536871594 = el.div(bassSound_536871566[0], bassGain_536871567[0]);
    var noise1_536871595 = el.lowpass(el.const({value: 8000.0}), el.const({value: 0.6}), el.mul(el.mul(el.pinknoise(), el.add(el.cycle((bpm_536871026 / 60.0)), 3.0)), el.const({value: 0.03})));
    var bpm2_536871596 = (bpm_536871026 / 120.0);
    var bpm4_536871597 = (bpm_536871026 / 240.0);
    var noise2_536871598 = el.lowpass(el.mul(el.mul(el.sub(1.0, el.train(bpm2_536871596)), el.add(0.2, el.phasor(bpm2_536871596))), 10000.0), el.const({value: 0.8}), el.mul(el.mul(el.mul(el.mul(el.sub(1.0, el.train(bpm2_536871596)), el.noise()), el.sub(1.0, el.pow(el.phasor(bpm2_536871596), 0.3))), 0.07), el.add(1.0, el.mul(-0.3, el.cycle(bpm4_536871597)))));
    result_536871350 = el.add(el.add(el.mul(bass_536871594, 0.8), noise1_536871595), noise2_536871598);

  return result_536871350;

}
var s_536870916 = scale_687866485({Field0: 10, Field1: 2}, 1);
var bassNull_536870917 = 0;
var bassA_536870955 = [nimCopy(null, note_536870918(3, 1), NTI536870926), nimCopy(null, brk_536870947(1.0), NTI536870926), nimCopy(null, note_536870918(3, 2), NTI536870926), nimCopy(null, note_536870918(1, 5), NTI536870926), nimCopy(null, note_536870918(3, 1), NTI536870926), nimCopy(null, brk_536870947(1.0), NTI536870926), nimCopy(null, note_536870918(3, 2), NTI536870926), nimCopy(null, note_536870918(1, 5), NTI536870926), nimCopy(null, note_536870918(3, 1), NTI536870926), nimCopy(null, brk_536870947(1.0), NTI536870926), nimCopy(null, note_536870918(3, 5), NTI536870926), nimCopy(null, note_536870918(1, 1), NTI536870926), nimCopy(null, note_536870918(3, 4), NTI536870926), nimCopy(null, brk_536870947(1.0), NTI536870926), nimCopy(null, note_536870918(3, 4), NTI536870926), nimCopy(null, brk_536870947(1.0), NTI536870926), nimCopy(null, sharp_536870942(note_536870918(3, 6)), NTI536870926), nimCopy(null, note_536870918(1, 2), NTI536870926), nimCopy(null, note_536870918(3, 4), NTI536870926), nimCopy(null, note_536870918(1, 7), NTI536870926), nimCopy(null, note_536870918(3, 3), NTI536870926), nimCopy(null, brk_536870947(1.0), NTI536870926), nimCopy(null, note_536870918(3, 2), NTI536870926), nimCopy(null, note_536870918(1, 5), NTI536870926), nimCopy(null, note_536870918(2, 1), NTI536870926), nimCopy(null, sharp_536870942(note_536870918(2, 3)), NTI536870926), nimCopy(null, note_536870918(3, 2), NTI536870926), nimCopy(null, brk_536870947(1.0), NTI536870926)];
var bassB_536870960 = [nimCopy(null, note_536870918(3, 5), NTI536870926), nimCopy(null, brk_536870947(1.0), NTI536870926), nimCopy(null, note_536870918(2, 1), NTI536870926), nimCopy(null, sharp_536870942(note_536870918(2, 3)), NTI536870926), nimCopy(null, note_536870918(3, 4), NTI536870926), nimCopy(null, brk_536870947(1.0), NTI536870926), nimCopy(null, note_536870918(3, 4), NTI536870926), nimCopy(null, brk_536870947(1.0), NTI536870926), nimCopy(null, note_536870918(3, 4), NTI536870926), nimCopy(null, sharp_536870942(note_536870918(1, 1)), NTI536870926), nimCopy(null, note_536870918(3, 7), NTI536870926), nimCopy(null, brk_536870947(1.0), NTI536870926), nimCopy(null, note_536870918(3, 3), NTI536870926), nimCopy(null, brk_536870947(1.0), NTI536870926), nimCopy(null, note_536870918(3, 2), NTI536870926), nimCopy(null, note_536870918(1, 5), NTI536870926)];
var bassA2_536870965 = [nimCopy(null, note_536870918(3, 1), NTI536870926), nimCopy(null, brk_536870947(1.0), NTI536870926), nimCopy(null, note_536870918(3, 2), NTI536870926), nimCopy(null, note_536870918(1, 5), NTI536870926), nimCopy(null, note_536870918(3, 1), NTI536870926), nimCopy(null, brk_536870947(1.0), NTI536870926), nimCopy(null, note_536870918(3, 2), NTI536870926), nimCopy(null, note_536870918(1, 5), NTI536870926), nimCopy(null, note_536870918(3, 1), NTI536870926), nimCopy(null, sharp_536870942(note_536870918(1, 6)), NTI536870926), nimCopy(null, note_536870918(3, 6), NTI536870926), nimCopy(null, note_536870918(1, 5), NTI536870926), nimCopy(null, note_536870918(3, 1), NTI536870926), nimCopy(null, brk_536870947(1.0), NTI536870926), nimCopy(null, note_536870918(3, 2), NTI536870926), nimCopy(null, brk_536870947(1.0), NTI536870926)];
var bassSong_536871025 = HEX26_536870966(HEX26_536870966(HEX26_536870966(bassA_536870955, bassA_536870955), bassB_536870960), bassA2_536870965);
var bpm_536871026 = 105.0;
var release_536871027 = 2.5;
var bassSeq_536871347 = [createSequencer_536871109(toSequence_536871030(bassSong_536871025, bassNull_536870917), bassNull_536870917, 2, bpm_536871026, 0, 0.0, [98,97,115,115], false)];
export {play_536871348 as play}
