/* Generated by the Nim Compiler v2.0.4 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
import { el } from "@elemaudio/core" 

function play_536870914(time_536870915) {
  var result_536870916 = null;

    result_536870916 = el.cycle(440.0);

  return result_536870916;

}
export {play_536870914 as play}
